version: '3'
services:
  node:
    build: ./
    restart: always
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    volumes:
      - ./src:/usr/app/src
      - node_modules:/usr/node/app/node_modules
      - ./logs:/home/node/app/logs
    networks:
      - my-network
  postgres:
    build: ./database/
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - dbdata:/data/db
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
volumes:
  dbdata:
  node_modules:
  pgadmin:
